# This script includes the functions that produce the shadow plots in the first simulation study.

# load & prepare Breslow estimators ############################################

# load Breslow estimators generated by the script 'simulations_calendar_times.R'
load("[path]/[name].RData") # TODO: adapt file name
breslow_list <- list(list(breslow_HR1_scenario1_standard, breslow_HR1_scenario1_model1, breslow_HR1_scenario1_model2),
                     list(breslow_HR1_scenario2_standard, breslow_HR1_scenario2_model1, breslow_HR1_scenario2_model2),
                     list(breslow_HR1_scenario3_standard, breslow_HR1_scenario3_model1, breslow_HR1_scenario3_model2),
                     list(breslow_HR1_scenario4_standard, breslow_HR1_scenario4_model1, breslow_HR1_scenario4_model2),
                     list(breslow_HR1_scenario5_standard, breslow_HR1_scenario5_model1, breslow_HR1_scenario5_model2),
                     list(breslow_HR1_scenario6_standard, breslow_HR1_scenario6_model1, breslow_HR1_scenario6_model2),
                     list(breslow_HR1_scenario7_standard, breslow_HR1_scenario7_model1, breslow_HR1_scenario7_model2),
                     list(breslow_HR1_scenario8_standard, breslow_HR1_scenario8_model1, breslow_HR1_scenario8_model2),
                     list(breslow_HR1_scenario9_standard, breslow_HR1_scenario9_model1, breslow_HR1_scenario9_model2),
                     list(breslow_HR1_scenario10_standard, breslow_HR1_scenario10_model1, breslow_HR1_scenario10_model2))
indicator_list <- list(indicator_HR1_scenario1, indicator_HR1_scenario2, indicator_HR1_scenario3, indicator_HR1_scenario4, indicator_HR1_scenario5, 
                       indicator_HR1_scenario6, indicator_HR1_scenario7, indicator_HR1_scenario8, indicator_HR1_scenario9, indicator_HR1_scearnio10)

# ATTENTION: this removes all other files from the workspace
rm(list=setdiff(ls(), c("breslow_list", "indicator_list")))

library(parallel)
library(pbapply)

# prepare data
for(i in 1:10){
  for(j in 1:3){
    
    # save values as matrix
    breslow <- breslow_list[[i]][[j]]
    matrix <- do.call(rbind, 
                      lapply(
                        seq_along(breslow), 
                        function(iter){breslow[[iter]] <- 
                          rbind(c(0,0,iter), cbind(subset(breslow[[iter]], time >= 0), iter))}
                      )
    )
    matrix <- subset(matrix, iter %in% which(indicator_list[[i]] == 1))
    
    # compute mean and median hazard rate
    ## TODO
    ## adapt the number of cores according to your needs
    cl <- makeCluster(detectCores() - 1, type="SOCK")
    clusterExport(cl, "matrix")
    clusterEvalQ(cl, library(dplyr))
    mean_median <- 
      matrix(unlist(
        pblapply(
          X = seq(0, quantile(matrix$time, 0.995), length.out = 1000), 
          FUN = function(x){
            haz <- matrix %>% group_by(iter) %>% 
              filter(time <= x) %>% filter(time == max(time)) %>% 
              pull(hazard)
            c(x, mean(haz), median(haz))
          }, 
          cl = cl
        )
      ), ncol = 3, byrow = T)
    stopCluster(cl)
    mean_median <- 
      data.frame(
        time = mean_median[,1], 
        mean = mean_median[,2], median = mean_median[,3]
      )
    
    k <- switch(j, 
                "standard", "model1", "model2")
    assign(paste0("breslow_scenario", i, "_", k), matrix, envir = .GlobalEnv)
    assign(paste0("breslow_scenario", i, "_", k, "_mean_median"), mean_median, 
           envir = .GlobalEnv)
    
  }
}

# select 2000 random iterations from each scenario
set.seed(123456)
for(i in 1:10){
  assign(paste0("sample_scenario", i), sample(which(indicator_list[[i]] == 1), 2000), 
         envir = .GlobalEnv)
}

# ATTENTION: this removes all other files from the workspace
rm(list = c("breslow_list", "breslow", "matrix", "indicator_list", "cl", "mean_median", "i", "j", "k"))


# create shadowplots ###########################################################

# create shadow plot
shadowplots <- function(breslow_standard, breslow_standard_mean_median, 
                        breslow_model1, breslow_model1_mean_median, 
                        breslow_model2, breslow_model2_mean_median,
                        xlim, xticks, xlabels, ylim, yticks, ylabels,
                        hazard_exp){
  
  # input:
  ## breslow_[model] (model = standard/model1/model2):
  ##   breslow estimators in the specified model
  ## breslow_[model]_mean_median (model = standard/model1/model2):
  ##   means & medians of the breslow estimators in the specified model
  ## xlim: upper limit of x axis
  ## xticks: position of ticks on x axis
  ## xlabels: labels of ticks on x axis
  ## ylim: upper limit of y axis
  ## yticks: position of ticks on y axis
  ## ylabels: labels of ticks on y axis
  ## hazard_exp: exponent to calculate true cumulative baseline hazard 
  ##   (1 for exponential scenarios, 0.5 for Weibull scenarios)
  
  plot <- function(breslow, breslow_mean_median, model){
    ggplot() +
      geom_step(data = breslow, aes(x = time, y = hazard, group = factor(iter)), colour = "grey") +
      geom_line(aes(x = seq(0, xlim, length.out=100), y = seq(0, xlim, length.out=100)^hazard_exp, colour = "true"), size = 1.5, linetype = 1) +
      geom_line(data = breslow_mean_median, aes(x=time, y=mean, colour= "mean"), size = 1.2, linetype = 1) +
      geom_line(data = breslow_mean_median, aes(x=time, y=median, colour= "median"), size = 1.2, linetype = 2) +
      ggtitle(model) + labs(x = "Time", y = ifelse(model == "Standard Model", "Cumulative baseline hazard", "")) +
      scale_x_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0,xlim), breaks = xticks, labels = xlabels) +
      scale_y_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0,ylim), breaks = yticks, labels = ylabels) +
      scale_color_manual(name = "", limits = c("true", "mean", "median"),
                         values = c("true" = "chartreuse", "mean" = "black", "median" = "black"),
                         labels = c("true" = "True cumulative baseline hazard   ",
                                    "mean" = "Mean of the simulated curves   ",
                                    "median" = "Median of the simulated curves   ")) +
      scale_linetype_manual("", values = c(1, 1, 4)) +
      guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
      theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "gray95"),
            axis.text = element_text(colour = "black"), text = element_text(size = 23),
            axis.line = element_line(colour = "black"),
            axis.title.x = element_text(margin = margin(t=8, r=0, b=0, l=0)),
            axis.title.y = element_text(margin = margin(t=0, r=8, b=0, l=0)),
            plot.title = element_text(hjust = 0.5, size = 26),
            plot.margin =  unit(c(1,1,1,1), "lines"))
  }
  
  p1 <- plot(breslow_standard, breslow_standard_mean_median, "Standard Model")
  p2 <- plot(breslow_model1, breslow_model1_mean_median, "Model 1")
  p3 <- plot(breslow_model2, breslow_model2_mean_median, "Model 2")
  
  grid.arrange(grobs = list(p1 + theme(legend.position = "none"), 
                            p2 + theme(legend.position = "none"), 
                            p3 + theme(legend.position = "none"),
                            get_legend(p1 + guides(colour = guide_legend(nrow = 1)) +
                                         theme(legend.key = element_rect(fill = NA)))), 
               layout_matrix = matrix(c(1,2,3, 4,4,4), byrow = TRUE, nrow = 2),
               heights = c(0.8, 0.2))

}


# execution ####################################################################

library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)

## Exponential scenario, n = 600, m = 300 ####
shadowplots(breslow_scenario1_standard[breslow_scenario1_standard$iter %in% sample_scenario1,], breslow_scenario1_standard_mean_median, 
            breslow_scenario1_model1[breslow_scenario1_model1$iter %in% sample_scenario1,], breslow_scenario1_model1_mean_median, 
            breslow_scenario1_model2[breslow_scenario1_model2$iter %in% sample_scenario1,], breslow_scenario1_model2_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

## Exponential scenario, n = 300, m = 150 ####
shadowplots(breslow_scenario2_standard[breslow_scenario2_standard$iter %in% sample_scenario2,], breslow_scenario2_standard_mean_median, 
            breslow_scenario2_model1[breslow_scenario2_model1$iter %in% sample_scenario2,], breslow_scenario2_model1_mean_median, 
            breslow_scenario2_model2[breslow_scenario2_model2$iter %in% sample_scenario2,], breslow_scenario2_model2_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

## Exponential scenario, n = 50, m = 25 ####
shadowplots(breslow_scenario3_standard[breslow_scenario3_standard$iter %in% sample_scenario3,], breslow_scenario3_standard_mean_median, 
            breslow_scenario3_model1[breslow_scenario3_model1$iter %in% sample_scenario3,], breslow_scenario3_model1_mean_median, 
            breslow_scenario3_model2[breslow_scenario3_model2$iter %in% sample_scenario3,], breslow_scenario3_model2_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

## Exponential scenario, n = 50, m = 10 ####
shadowplots(breslow_scenario4_standard[breslow_scenario4_standard$iter %in% sample_scenario4,], breslow_scenario4_standard_mean_median, 
            breslow_scenario4_model1[breslow_scenario4_model1$iter %in% sample_scenario4,], breslow_scenario4_model1_mean_median, 
            breslow_scenario4_model2[breslow_scenario4_model2$iter %in% sample_scenario4,], breslow_scenario4_model2_mean_median,
            xlim = 0.4, xticks = c(0.0, 0.1, 0.2, 0.3, 0.4), xlabels = c("0.0", "", "0.2", "", "0.4"),
            ylim = 0.6, yticks = seq(0, 0.6, 0.06), ylabels = c("0.0", "", "", "", "", "0.3", "", "", "", "", "0.6"),
            hazard_exp = 1)

## Exponential scenario, n = 26, m = 13 ####
shadowplots(breslow_scenario5_standard[breslow_scenario5_standard$iter %in% sample_scenario5,], breslow_scenario5_standard_mean_median, 
            breslow_scenario5_model1[breslow_scenario5_model1$iter %in% sample_scenario5,], breslow_scenario5_model1_mean_median, 
            breslow_scenario5_model2[breslow_scenario5_model2$iter %in% sample_scenario5,], breslow_scenario5_model2_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

## Weibull scenario, n = 600, m = 300 ####
shadowplots(breslow_scenario6_standard[breslow_scenario6_standard$iter %in% sample_scenario6,], breslow_scenario6_standard_mean_median, 
            breslow_scenario6_model1[breslow_scenario6_model1$iter %in% sample_scenario6,], breslow_scenario6_model1_mean_median, 
            breslow_scenario6_model2[breslow_scenario6_model2$iter %in% sample_scenario6,], breslow_scenario6_model2_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)

## Weibull scenario, n = 300, m = 150 ####
shadowplots(breslow_scenario7_standard[breslow_scenario7_standard$iter %in% sample_scenario7,], breslow_scenario7_standard_mean_median, 
            breslow_scenario7_model1[breslow_scenario7_model1$iter %in% sample_scenario7,], breslow_scenario7_model1_mean_median, 
            breslow_scenario7_model2[breslow_scenario7_model2$iter %in% sample_scenario7,], breslow_scenario7_model2_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)

## Weibull scenario, n = 50, m = 25 ####
shadowplots(breslow_scenario8_standard[breslow_scenario8_standard$iter %in% sample_scenario8,], breslow_scenario8_standard_mean_median, 
            breslow_scenario8_model1[breslow_scenario8_model1$iter %in% sample_scenario8,], breslow_scenario8_model1_mean_median, 
            breslow_scenario8_model2[breslow_scenario8_model2$iter %in% sample_scenario8,], breslow_scenario8_model2_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)

## Weibull scenario, n = 50, m = 10 ####
shadowplots(breslow_scenario9_standard[breslow_scenario9_standard$iter %in% sample_scenario9,], breslow_scenario9_standard_mean_median, 
            breslow_scenario9_model1[breslow_scenario9_model1$iter %in% sample_scenario9,], breslow_scenario9_model1_mean_median, 
            breslow_scenario9_model2[breslow_scenario9_model2$iter %in% sample_scenario9,], breslow_scenario9_model2_mean_median,
            xlim = 0.1, xticks = c(0, 0.025, 0.05, 0.075, 0.1), xlabels = c("0.0", "", "0.05", "", "0.1"),
            ylim = 0.4, yticks = seq(0, 0.4, 0.04), ylabels = c("0", "", "", "", "", "0.2", "", "", "", "", "0.4"),
            hazard_exp = 0.5)

## Weibull scenario, n = 26, m = 13 ####
shadowplots(breslow_scenario10_standard[breslow_scenario10_standard$iter %in% sample_scenario10,], breslow_scenario10_standard_mean_median, 
            breslow_scenario10_model1[breslow_scenario10_model1$iter %in% sample_scenario10,], breslow_scenario10_model1_mean_median, 
            breslow_scenario10_model2[breslow_scenario10_model2$iter %in% sample_scenario10,], breslow_scenario10_model2_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)
