# This script includes the functions that produce the shadow plots in the first simulation study.

# load & prepare Breslow estimators #########################

# load Breslow estimators generated by the script 'simulations_calendar_times.R'
load("simulations.RData") # TODO: adapt file name
breslow_list <- list(list(breslow_standard_1, breslow_model1_1, breslow_model2_1),
                     list(breslow_standard_2, breslow_model1_2, breslow_model2_2),
                     list(breslow_standard_3, breslow_model1_3, breslow_model2_3),
                     list(breslow_standard_4, breslow_model1_4, breslow_model2_4),
                     list(breslow_standard_5, breslow_model1_5, breslow_model2_5),
                     list(breslow_standard_6, breslow_model1_6, breslow_model2_6))
indicator_list <- list(NA, indicator_2, indicator_3, NA, indicator_5, indicator_6)

# ATTENTION: this removes all unnecessary files from workspace
rm(list=setdiff(ls(), c("breslow_list", "indicator_list")))

library(parallel)
library(pbapply)

# prepare data
for(i in 1:6){
  for(j in 1:3){
    
    # save values as matrix
    breslow <- breslow_list[[i]][[j]]
    matrix <- do.call(rbind, 
                      lapply(
                        seq_along(breslow), 
                        function(iter){breslow[[iter]] <- rbind(c(0,0,iter), cbind(subset(breslow[[iter]], time >= 0), iter))}
                      )
    )
    if(i %in% c(2,3,5,6)){
      matrix <- subset(matrix, iter %in% which(indicator_list[[i]] == 1))
    }
    
    # compute mean and median hazard rate
    ## TODO 
    ## adapt the number of cores according to your needs
    cl <- makeCluster(detectCores() - 1, type="SOCK")
    clusterExport(cl, "matrix")
    clusterEvalQ(cl, library(dplyr))
    mean_median <- 
      matrix(unlist(
        pblapply(
          X = seq(0, quantile(matrix$time, 0.995), length.out = 1000), 
          FUN = function(x){
            haz <- matrix %>% group_by(iter) %>% 
              filter(time <= x) %>% filter(time == max(time)) %>% 
              pull(hazard)
            c(x, mean(haz), median(haz))
          }, 
          cl = cl
        )
      ), ncol = 3, byrow = T)
    stopCluster(cl)
    mean_median <- 
      data.frame(
        time = mean_median[,1], 
        mean = mean_median[,2], median = mean_median[,3]
      )
    
    k <- switch(j, 
                "standard", "model1", "model2")
    assign(paste0("breslow_", k, "_", i), matrix, envir = .GlobalEnv)
    assign(paste0("breslow_", k, "_", i, "_mean_median"), mean_median, envir = .GlobalEnv)
    
  }
}

rm(list = c("breslow_list", "breslow", "matrix", "cl", "mean_median", "i", "j", "k"))


# compute bias at selected time points #########################################

mean_bias1 <- mean_bias2 <- mean_bias3 <- mean_bias4 <- mean_bias5 <- mean_bias6 <- matrix(NA, nrow = 3, ncol = 3)
median_bias1 <- median_bias2 <- median_bias3 <- median_bias4 <- median_bias5 <- median_bias6 <- matrix(NA, nrow = 3, ncol = 3)
RMSE1 <- RMSE2 <- RMSE3 <- RMSE4 <- RMSE5 <- RMSE6 <- matrix(NA, nrow = 3, ncol = 3)
for(j in 1:6){
  times <- switch(j, 
                  c(0.3, 0.6, 0.9),
                  c(0.1, 0.2, 0.3),
                  c(0.3, 0.6, 0.9),
                  c(0.2, 0.45, 0.7),
                  c(0.03, 0.05, 0.07),
                  c(0.2, 0.45, 0.7)
  )
  exp <- switch(j, 1, 1, 1, 0.5, 0.5, 0.5)
  i <- 1
  for(t in times){
    
    eval(parse(text=paste0("mean_bias", j, "[", i, ",1] <- breslow_standard_", j, "_mean_median[findInterval(t, breslow_standard_", j, "_mean_median$time),'mean'] - t^exp")))
    eval(parse(text=paste0("mean_bias", j, "[", i, ",2] <- breslow_model1_", j, "_mean_median[findInterval(t, breslow_model1_", j, "_mean_median$time),'mean'] - t^exp")))
    eval(parse(text=paste0("mean_bias", j, "[", i, ",3] <- breslow_model2_", j, "_mean_median[findInterval(t, breslow_model2_", j, "_mean_median$time),'mean'] - t^exp")))
    
    eval(parse(text=paste0("median_bias", j, "[", i, ",1] <- breslow_standard_", j, "_mean_median[findInterval(t, breslow_standard_", j, "_mean_median$time),'median'] - t^exp")))
    eval(parse(text=paste0("median_bias", j, "[", i, ",2] <- breslow_model1_", j, "_mean_median[findInterval(t, breslow_model1_", j, "_mean_median$time),'median'] - t^exp")))
    eval(parse(text=paste0("median_bias", j, "[", i, ",3] <- breslow_model2_", j, "_mean_median[findInterval(t, breslow_model2_", j, "_mean_median$time),'median'] - t^exp")))
    
    eval(parse(text=paste0("RMSE", j, "[", i, ",1] <- sqrt(mean(breslow_standard_", j, " %>% group_by(iter) %>% filter(time <= t) %>% filter(time == max(time)) %>% pull(hazard) - t^exp)^2)")))
    eval(parse(text=paste0("RMSE", j, "[", i, ",2] <- sqrt(mean(breslow_model1_", j, " %>% group_by(iter) %>% filter(time <= t) %>% filter(time == max(time)) %>% pull(hazard) - t^exp)^2)")))
    eval(parse(text=paste0("RMSE", j, "[", i, ",3] <- sqrt(mean(breslow_model2_", j, " %>% group_by(iter) %>% filter(time <= t) %>% filter(time == max(time)) %>% pull(hazard) - t^exp)^2)")))
    
    i <- i + 1
  }
}
colnames(mean_bias1) <- colnames(mean_bias2) <- colnames(mean_bias3) <- colnames(mean_bias4) <- colnames(mean_bias5) <- colnames(mean_bias6) <- 
  c("Standard Model", "Model 1", "Model 2")
colnames(median_bias1) <- colnames(median_bias2) <- colnames(median_bias3) <- colnames(median_bias4) <- colnames(median_bias5) <- colnames(median_bias6) <- 
  c("Standard Model", "Model 1", "Model 2")
colnames(RMSE1) <- colnames(RMSE2) <- colnames(RMSE3) <- colnames(RMSE4) <- colnames(RMSE5) <- colnames(RMSE6) <- 
  c("Standard Model", "Model 1", "Model 2")


# create shadowplots ###########################################################

library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)

# select 2000 random iterations from each scenario
set.seed(123456)
for(i in 1:6){
  if(i %in% c(1,4)){
    sample <- sample(1:100000, 2000)
  }else{
    sample <- sample(which(indicator_list[[i]] == 1), 2000)
  }
  assign(paste0("sample_", i), sample, envir = .GlobalEnv)
}

# create shadow plots
shadowplots <- function(breslow_standard, breslow_standard_mean_median, 
                        breslow_model1, breslow_model1_mean_median, 
                        breslow_model2, breslow_model2_mean_median,
                        xlim, xticks, xlabels, ylim, yticks, ylabels,
                        hazard_exp){
  
  # input:
  ## breslow_[model] (model = standard/model1/model2):
  ##   breslow estimators in the specified model
  ## breslow_[model]_mean_median (model = standard/model1/model2):
  ##   means & medians of the breslow estimators in the specified model
  ## xlim: upper limit of x axis
  ## xticks: position of ticks on x axis
  ## xlabels: labels of ticks on x axis
  ## ylim: upper limit of y axis
  ## yticks: position of ticks on y axis
  ## ylabels: labels of ticks on y axis
  ## hazard_exp: exponent to calculate true cumulative baseline hazard 
  ##   (1 for exponential scenarios, 0.5 for Weibull scenarios)
  
  p1 <-
    ggplot() +
    geom_step(data = breslow_standard, aes(x = time, y = hazard, group = factor(iter)), colour = "grey") +
    geom_line(aes(x = seq(0, xlim, length.out = 100), y = seq(0, xlim, length.out = 100)^hazard_exp, colour = "true"), size = 1.5, linetype = 1) +
    geom_line(data = breslow_standard_mean_median, aes(x=time, y=mean, colour= "mean"), size = 1.2, linetype = 1) +
    geom_line(data = breslow_standard_mean_median, aes(x=time, y=median, colour= "median"), size = 1.2, linetype = 2) +
    ggtitle("Standard Model") + labs(x = "Time", y = "Cumulative baseline hazard") +
    scale_x_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, xlim), breaks = xticks, labels = xlabels) +
    scale_y_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, ylim), breaks = yticks, labels = ylabels) +
    scale_color_manual(name = "", limits = c("true", "mean", "median"),
                       values = c("true" = "chartreuse", "mean" = "black", "median" = "black"),
                       labels = c("true" = "True cumulative baseline hazard   ",
                                  "mean" = "Mean of the simulated curves   ",
                                  "median" = "Median of the simulated curves   ")) +
    scale_linetype_manual("", values = c(1, 1, 4)) +
    guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
    theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "gray95"),
          axis.text = element_text(colour = "black"), text = element_text(size = 23),
          axis.line = element_line(colour = "black"),
          axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0)),
          axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0)),
          plot.title = element_text(hjust = 0.5, size = 26),
          plot.margin =  unit(c(1,1,1,1), "lines"))
  
  p2 <-
    ggplot() +
    geom_step(data = breslow_model1, aes(x = time, y = hazard, group = factor(iter)), colour = "grey") +
    geom_line(aes(x = seq(0, xlim, length.out = 100), y = seq(0, xlim, length.out = 100)^hazard_exp, colour = "true"), size = 1.5, linetype = 1) +
    geom_line(data = breslow_model1_mean_median, aes(x=time, y=mean, colour= "mean"), size = 1.2, linetype = 1) +
    geom_line(data = breslow_model1_mean_median, aes(x=time, y=median, colour= "median"), size = 1.2, linetype = 2) +
    ggtitle("Model 1") + labs(x = "Time", y = "") +
    scale_x_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, xlim), breaks = xticks, labels = xlabels) +
    scale_y_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, ylim), breaks = yticks, labels = ylabels) +
    scale_color_manual(name = "", limits = c("true", "mean", "median"),
                       values = c("true" = "chartreuse", "mean" = "black", "median" = "black")) +
    scale_linetype_manual("", values = c(1, 1, 4)) +
    guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
    theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "gray95"),
          axis.text = element_text(colour = "black"), text = element_text(size = 23),
          axis.line = element_line(colour = "black"),
          axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0)),
          axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0)),
          plot.title = element_text(hjust = 0.5, size = 26),
          plot.margin =  unit(c(1,1,1,1), "lines"))
  
  p3 <-
    ggplot() +
    geom_step(data = breslow_model2, aes(x = time, y = hazard, group = factor(iter)), colour = "grey") +
    geom_line(aes(x = seq(0, xlim, length.out = 100), y = seq(0, xlim, length.out = 100)^hazard_exp, colour = "true"), size = 1.5, linetype = 1) +
    geom_line(data = breslow_model2_mean_median, aes(x=time, y=mean, colour= "mean"), size = 1.2, linetype = 1) +
    geom_line(data = breslow_model2_mean_median, aes(x=time, y=median, colour= "median"), size = 1.2, linetype = 2) +
    ggtitle("Model 2") + labs(x = "Time", y = "") +
    scale_x_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, xlim), breaks = xticks, labels = xlabels) +
    scale_y_continuous(expand = expansion(mult = c(0.03,0)), limits = c(0, ylim), breaks = yticks, labels = ylabels) +
    scale_color_manual(name = "", limits = c("true", "mean", "median"),
                       values = c("true" = "chartreuse", "mean" = "black", "median" = "black")) +
    scale_linetype_manual("", values = c(1, 1, 4)) +
    guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
    theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "gray95"),
          axis.text = element_text(colour = "black"), text = element_text(size = 23),
          axis.line = element_line(colour = "black"),
          axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0)),
          axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0)),
          plot.title = element_text(hjust = 0.5, size = 26),
          plot.margin =  unit(c(1,1,1,1), "lines")) 
  
  layout <- matrix(c(1,2,3, 4,4,4), byrow = TRUE, nrow = 2)
  grid.arrange(grobs = list(p1 + theme(legend.position = "none"), 
                            p2 + theme(legend.position = "none"), 
                            p3 + theme(legend.position = "none"),
                            get_legend(p1 + guides(colour = guide_legend(nrow = 1)) +
                                         theme(legend.key = element_rect(fill = NA)))), 
               layout_matrix = layout,
               heights = c(0.8, 0.2))

}

shadowplots(breslow_standard_1[breslow_standard_1$iter %in% sample_1,], breslow_standard_1_mean_median, 
            breslow_model1_1[breslow_model1_1$iter %in% sample_1,], breslow_model1_1_mean_median, 
            breslow_model2_1[breslow_model2_1$iter %in% sample_1,], breslow_model2_1_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

shadowplots(breslow_standard_2[breslow_standard_2$iter %in% sample_2,], breslow_standard_2_mean_median, 
            breslow_model1_2[breslow_model1_2$iter %in% sample_2,], breslow_model1_2_mean_median, 
            breslow_model2_2[breslow_model2_2$iter %in% sample_2,], breslow_model2_2_mean_median,
            xlim = 0.4, xticks = c(0.0, 0.1, 0.2, 0.3, 0.4), xlabels = c("0.0", "", "0.2", "", "0.4"),
            ylim = 0.6, yticks = seq(0, 0.6, 0.06), ylabels = c("0.0", "", "", "", "", "0.3", "", "", "", "", "0.6"),
            hazard_exp = 1)

shadowplots(breslow_standard_3[breslow_standard_3$iter %in% sample_3,], breslow_standard_3_mean_median, 
            breslow_model1_3[breslow_model1_3$iter %in% sample_3,], breslow_model1_3_mean_median, 
            breslow_model2_3[breslow_model2_3$iter %in% sample_3,], breslow_model2_3_mean_median,
            xlim = 1.2, xticks = c(0.0, 0.4, 0.8, 1.2), xlabels = c("0.0", "0.4", "0.8", "1.2"),
            ylim = 1.35, yticks = seq(0, 1.35, 0.15), ylabels = c("0.0", "", "", "", "0.6", "", "", "", "1.2", ""),
            hazard_exp = 1)

shadowplots(breslow_standard_4[breslow_standard_4$iter %in% sample_4,], breslow_standard_4_mean_median, 
            breslow_model1_4[breslow_model1_4$iter %in% sample_4,], breslow_model1_4_mean_median, 
            breslow_model2_4[breslow_model1_4$iter %in% sample_4,], breslow_model2_4_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)

shadowplots(breslow_standard_5[breslow_standard_5$iter %in% sample_5,], breslow_standard_5_mean_median, 
            breslow_model1_5[breslow_model1_5$iter %in% sample_5,], breslow_model1_5_mean_median, 
            breslow_model2_5[breslow_model1_5$iter %in% sample_5,], breslow_model2_5_mean_median,
            xlim = 0.1, xticks = c(0, 0.025, 0.05, 0.075, 0.1), xlabels = c("0.0", "", "0.05", "", "0.1"),
            ylim = 0.4, yticks = seq(0, 0.4, 0.04), ylabels = c("0", "", "", "", "", "0.2", "", "", "", "", "0.4"),
            hazard_exp = 0.5)

shadowplots(breslow_standard_6[breslow_standard_6$iter %in% sample_6,], breslow_standard_6_mean_median, 
            breslow_model1_6[breslow_model1_6$iter %in% sample_6,], breslow_model1_6_mean_median, 
            breslow_model2_6[breslow_model2_6$iter %in% sample_6,], breslow_model2_6_mean_median,
            xlim = 0.9, xticks = c(0.0, 0.3, 0.6, 0.9), xlabels = c("0.0", "0.3", "0.6", "0.9"),
            ylim = 1, yticks = seq(0, 1, 0.1), ylabels = c("0", "", "", "0.3", "", "", "0.6", "", "", "0.9", ""),
            hazard_exp = 0.5)
